*&---------------------------------------------------------------------*
*&  Include           SAPDZH24_TOP
*&---------------------------------------------------------------------*
TABLES : zsits_scan_dynp.

TYPES :   BEGIN OF ts_message,
            message1 TYPE char20,
            message2 TYPE char20,
            message3 TYPE char20,
            message4 TYPE char20,
            message5 TYPE char20,
            message6 TYPE char20,
            message7 TYPE char20,
            message8 TYPE char20,
          END OF ts_message .

TYPES : BEGIN OF lty_hu,
          hu    TYPE char100, " HU
          p_hu  TYPE char100, " Parent HU
          label TYPE char5, " Label for Pallete or carton
        END OF lty_hu.

TYPES :       BEGIN OF ts_exidv,
                hu1 TYPE exidv,
                hu2 TYPE exidv,
                hu3 TYPE exidv,
              END OF ts_exidv.

TYPES : BEGIN OF lty_lfart,
          lfart TYPE lfart,
        END OF lty_lfart.

TYPES: BEGIN OF gty_cart_all,
         barcode TYPE zl_de_old_hu,
         exidv   TYPE exidv,
         lfimg   TYPE lfimg,
         batch   TYPE charg_d,
       END OF gty_cart_all.

TYPES: BEGIN OF lty_lips,
         posnr TYPE posnr_vl,
         matnr TYPE matnr,
         werks TYPE werks_d,
         charg TYPE charg_d,
         lfimg TYPE lfimg,
         meins TYPE meins,
         vrkme TYPE vrkme,
         lgnum TYPE lgnum,
         lgtyp TYPE lgtyp,
         mtart TYPE mtart,
       END OF lty_lips.

TYPES: BEGIN OF lty_hu_n,
         hu1  TYPE zd_barcode,
         hu2  TYPE zd_barcode,
         hu3  TYPE zd_barcode,
         hu4  TYPE zd_barcode,
         qty1 TYPE lfimg,
         qty2 TYPE lfimg,
         qty3 TYPE lfimg,
         qty4 TYPE lfimg,
       END OF lty_hu_n.

TYPES: BEGIN OF ty_hu,
         typ(1)  TYPE c,
         hu      TYPE zd_hu_exid,
         qty(14) TYPE c,
         batch   TYPE charg_d,
         flag    TYPE flag,
       END OF ty_hu .

TYPES: BEGIN OF lty_final,
         zzbarcode TYPE zl_de_old_hu,
         lfimg     TYPE lfimg,
         count     TYPE sy-index,
         batch     TYPE charg_d,
       END OF lty_final.

 TYPES: BEGIN OF ts_werks_r,
           sign   TYPE ddsign,
           option TYPE ddoption,
           low    TYPE werks_d,
           high   TYPE werks_d,
         END OF ts_werks_r,
         tt_werks_r TYPE STANDARD TABLE OF ts_werks_r.

DATA:    lv_display(1) TYPE c,
         lv_error(1)   TYPE c,
         lv_return(50) TYPE c,
         lv_msg(20)    TYPE c,
         lt_hu         TYPE TABLE OF ty_hu,
         lv_type(3)    TYPE c.

DATA: ok_code          TYPE sy-ucomm,
      lt_cart_all      TYPE STANDARD TABLE OF gty_cart_all,
      v_barcode        TYPE zsits_scan_dynp-zzbarcode,
      go_hu            TYPE REF TO zcl_rfscanner_packunpack,
      v_flag           TYPE c,
      ls_likp          TYPE likp,
      lv_msgno         TYPE syst_msgno, "msgno,
      lv_msgv1         TYPE msgv1,
      lv_msgv2         TYPE msgv1,
      lv_msgv3         TYPE msgv1,
      lv_msgv4         TYPE msgv1,
      gv_message1      TYPE char20,
      gv_message2      TYPE char20,
      gv_message3      TYPE char20,
      gv_message4      TYPE char20,
      gv_message5      TYPE char20,
      gv_message6      TYPE char20,
      gv_message7      TYPE char20,
      gv_message8      TYPE char20,
      gv_barcode1      TYPE char100,
      gs_hu            TYPE zcl_rfscanner_packunpack=>ts_phu,
      it_hu            TYPE STANDARD TABLE OF lty_hu,
      lt_hu1           TYPE STANDARD TABLE OF ty_hu,
      lt_hu2           TYPE STANDARD TABLE OF ty_hu,
      lt_hu4           TYPE STANDARD TABLE OF ty_hu,
      it_hu_link_obd   TYPE STANDARD TABLE OF lty_hu,
      ls_hu            TYPE lty_hu,
      v_hu_counter     TYPE i,
      v_hu_txt         TYPE char3,
      gs_label_content TYPE zsits_label_content,
      gt_exidv         TYPE TABLE OF ts_exidv,
      gv_hu1           TYPE exidv,
      gv_hu2           TYPE exidv,
      gv_hu3           TYPE exidv,
      gv_index         TYPE sy-index,
      gv_delivery      TYPE zsits_scan_dynp-zzdestbin,
      lv_check         TYPE boolean,
      lt_param         TYPE STANDARD TABLE OF zvv_param,
      ls_param         TYPE zvv_param,
      lit_lfart        TYPE STANDARD TABLE OF lty_lfart,
      ls_lfart         TYPE lty_lfart,
      lit_lfart_all    TYPE TABLE OF lty_lfart,
      lit_lfart_r      TYPE STANDARD TABLE OF lfart_range,
      gv_qty           TYPE lfimg,
      gv_cart1         TYPE zl_de_old_hu,
      gv_cart1_barcode TYPE zl_de_old_hu,
      gv_cart2_barcode TYPE zl_de_old_hu,
      gv_cart3_barcode TYPE zl_de_old_hu,
      gv_cart4_barcode TYPE zl_de_old_hu,
      gv_cart2         TYPE zl_de_old_hu,
      gv_cart3         TYPE zl_de_old_hu,
      gv_cart4         TYPE zl_de_old_hu,
      gv_palqty        TYPE lips-lfimg,
      gv_pal           TYPE zl_de_old_hu,
      lv_cursor        TYPE char255,
      lv_cursor_n      TYPE char255,
*      gv_cart5         TYPE zd_barcode,
*      gv_cart6         TYPE zd_barcode,
*      gv_cart7         TYPE zd_barcode,
*      gv_cart8         TYPE zd_barcode,
      lt_scan_det      TYPE STANDARD TABLE OF zlscan_detail,
      lwa_lips         TYPE lty_lips,
      lt_lips          TYPE STANDARD TABLE OF lty_lips,
      gv_cart1_qty     TYPE char14, "lfimg,
      gv_cart2_qty     TYPE char14,
      gv_cart3_qty     TYPE char14, "lfimg,
      gv_cart4_qty     TYPE char14, "lfimg,
      lv_lfimg         TYPE char14, "lfimg,
      lwa_hu           TYPE lty_hu_n,
      li_hu_disp       TYPE STANDARD TABLE OF lty_hu_n,
      li_hu_disp_n     TYPE STANDARD TABLE OF lty_hu_n,
      lwa_final        TYPE lty_final,
      lt_cart          TYPE STANDARD TABLE OF lty_final,
      gv_gelatin       TYPE sy-tcode,
      gv_tcode         TYPE sy-tcode,
      gv_flg_pallet    TYPE flag,
      lv_count         TYPE sy-index,
      lv_indx          TYPE sy-index,
      gv_index1        TYPE i,
      gv_index2        TYPE i,
      gv_text          TYPE char100,
      gt_werks_r       TYPE tt_werks_r,
      ls_lfart_r       TYPE lfart_range.

CONSTANTS : gc_back        TYPE char4 VALUE 'BACK',
            gc_clr         TYPE char3 VALUE 'CLR',
            gc_f2          TYPE char2 VALUE 'F2',
            gc_f3          TYPE char2 VALUE 'F3',
            gc_enter       TYPE char5 VALUE 'ENTER',
            gc_next        TYPE char4 VALUE 'NEXT',
            gc_ent         TYPE char3 VALUE 'ENT',
            gc_save        TYPE char4 VALUE 'SAVE',
            gc_ok          TYPE char2  VALUE 'OK',
            gc_flag        TYPE char1  VALUE 'X',
            gc_msgid       TYPE msgid  VALUE 'ZLONE_HU',
            gc_msgid1      TYPE msgid  VALUE 'ZITS',
            gc_0(1)        TYPE c      VALUE '0',
            gc_msgno1      TYPE msgno VALUE '001',
            gc_lookup_name TYPE zvv_param-lookup_name VALUE 'ZWM_BLOB',
            gc_ob_type     TYPE zvv_param-free_key VALUE 'LFART'.
